; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jun 13 2019 22:27:58 GMT-0400 (EDT)
; ================================================================================

DATAJM0MRRWFIC:
	dc.w DATAJM0MRRWFIC_0-DATAJM0MRRWFIC, DATAJM0MRRWFIC_1-DATAJM0MRRWFIC
	dc.w DATAJM0MRRWFIC_2-DATAJM0MRRWFIC, DATAJM0MRRWFIC_3-DATAJM0MRRWFIC
DATAJM0MRRWFIC_0: dc.b $0, $1
	dc.b $FC, $0, $0, $0, $0, $0, $FF, $FC
DATAJM0MRRWFIC_1: dc.b $0, $1
	dc.b $F8, $5, $0, $1, $0, $0, $FF, $F8
DATAJM0MRRWFIC_2: dc.b $0, $1
	dc.b $F0, $F, $0, $5, $0, $2, $FF, $F0
DATAJM0MRRWFIC_3: dc.b $0, $4
	dc.b $E0, $F, $0, $15, $0, $A, $FF, $E0
	dc.b $0, $F, $0, $25, $0, $12, $FF, $E0
	dc.b $E0, $F, $0, $35, $0, $1A, $0, $0
	dc.b $0, $F, $0, $45, $0, $22, $0, $0
	even