; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jun 13 2019 22:26:55 GMT-0400 (EDT)
; ================================================================================

DATAEYODVCCXCNP:
	dc.w DATAEYODVCCXCNP_0-DATAEYODVCCXCNP, DATAEYODVCCXCNP_1-DATAEYODVCCXCNP
	dc.w DATAEYODVCCXCNP_2-DATAEYODVCCXCNP, DATAEYODVCCXCNP_3-DATAEYODVCCXCNP
	dc.w DATAEYODVCCXCNP_4-DATAEYODVCCXCNP, DATAEYODVCCXCNP_5-DATAEYODVCCXCNP
DATAEYODVCCXCNP_0: dc.b $0, $4
	dc.b $F0, $5, $20, $0, $20, $0, $FF, $F8
	dc.b $0, $A, $20, $4, $20, $2, $FF, $F8
	dc.b $18, $4, $20, $D, $20, $6, $0, $0
	dc.b $8, $0, $20, $F, $20, $7, $0, $10
DATAEYODVCCXCNP_1: dc.b $0, $5
	dc.b $F1, $6, $20, $10, $20, $8, $FF, $F1
	dc.b $9, $A, $20, $16, $20, $B, $FF, $F9
	dc.b $1, $0, $20, $1F, $20, $F, $0, $1
	dc.b $9, $0, $20, $20, $20, $10, $0, $11
	dc.b $1, $4, $20, $21, $20, $10, $0, $9
DATAEYODVCCXCNP_2: dc.b $0, $3
	dc.b $FC, $4, $20, $23, $20, $11, $FF, $F5
	dc.b $4, $E, $20, $25, $20, $12, $FF, $F5
	dc.b $1C, $0, $20, $31, $20, $18, $0, $5
DATAEYODVCCXCNP_3: dc.b $0, $4
	dc.b $F1, $6, $20, $32, $20, $19, $FF, $EA
	dc.b $1, $0, $20, $38, $20, $1C, $FF, $FA
	dc.b $9, $1, $20, $39, $20, $1C, $FF, $F2
	dc.b $9, $A, $20, $3B, $20, $1D, $FF, $FA
DATAEYODVCCXCNP_4: dc.b $0, $5
	dc.b $F3, $6, $20, $44, $20, $22, $FF, $F1
	dc.b $B, $A, $20, $4A, $20, $25, $FF, $F9
	dc.b $3, $0, $20, $53, $20, $29, $0, $1
	dc.b $B, $0, $20, $54, $20, $2A, $0, $11
	dc.b $3, $4, $20, $55, $20, $2A, $0, $9
DATAEYODVCCXCNP_5: dc.b $0, $1
	dc.b $FC, $0, $20, $57, $20, $2B, $FF, $FC
	even