; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jun 13 2019 23:27:49 GMT-0400 (EDT)
; ================================================================================

DATALH296N763C:
	dc.w DATALH296N763C_0-DATALH296N763C, DATALH296N763C_1-DATALH296N763C
	dc.w DATALH296N763C_2-DATALH296N763C, DATALH296N763C_3-DATALH296N763C
	dc.w DATALH296N763C_4-DATALH296N763C, DATALH296N763C_5-DATALH296N763C
	dc.w DATALH296N763C_6-DATALH296N763C, DATALH296N763C_7-DATALH296N763C
	dc.w DATALH296N763C_8-DATALH296N763C, DATALH296N763C_9-DATALH296N763C
	dc.w DATALH296N763C_A-DATALH296N763C, DATALH296N763C_B-DATALH296N763C
	dc.w DATALH296N763C_C-DATALH296N763C, DATALH296N763C_D-DATALH296N763C
	dc.w DATALH296N763C_E-DATALH296N763C, DATALH296N763C_F-DATALH296N763C
	dc.w DATALH296N763C_10-DATALH296N763C, DATALH296N763C_11-DATALH296N763C
	dc.w DATALH296N763C_12-DATALH296N763C, DATALH296N763C_13-DATALH296N763C
	dc.w DATALH296N763C_14-DATALH296N763C, DATALH296N763C_15-DATALH296N763C
	dc.w DATALH296N763C_16-DATALH296N763C, DATALH296N763C_17-DATALH296N763C
DATALH296N763C_0: dc.b $0, $1
	dc.b $E8, $C, $0, $0, $0, $0, $FF, $F1
DATALH296N763C_1: dc.b $0, $3
	dc.b $EC, $C, $0, $0, $0, $0, $FF, $EF
	dc.b $F2, $0, $0, $4, $0, $2, $0, $C
	dc.b $F1, $0, $0, $5, $0, $2, $0, $3
DATALH296N763C_2: dc.b $0, $3
	dc.b $F3, $8, $0, $0, $0, $0, $FF, $FF
	dc.b $F9, $4, $0, $3, $0, $1, $FF, $F0
	dc.b $F0, $4, $0, $1, $0, $0, $FF, $E6
DATALH296N763C_3: dc.b $0, $3
	dc.b $F4, $C, $0, $0, $0, $0, $FF, $E4
	dc.b $F7, $8, $0, $4, $0, $2, $FF, $F9
	dc.b $F3, $5, $0, $7, $0, $3, $FF, $F5
DATALH296N763C_4: dc.b $0, $4
	dc.b $F6, $C, $0, $0, $0, $0, $FF, $F2
	dc.b $FF, $8, $0, $4, $0, $2, $0, $0
	dc.b $FE, $C, $0, $7, $0, $3, $FF, $E7
	dc.b $5, $8, $0, $4, $0, $2, $FF, $F0
DATALH296N763C_5: dc.b $0, $4
	dc.b $4, $C, $0, $0, $0, $0, $FF, $F9
	dc.b $C, $4, $0, $0, $0, $0, $FF, $EF
	dc.b $0, $8, $0, $4, $0, $2, $FF, $DB
	dc.b $F6, $1, $0, $0, $0, $0, $FF, $F3
DATALH296N763C_6: dc.b $0, $4
	dc.b $3, $C, $0, $0, $0, $0, $FF, $DE
	dc.b $1, $4, $0, $1, $0, $0, $0, $D
	dc.b $5, $4, $0, $4, $0, $2, $FF, $FD
	dc.b $C, $0, $0, $6, $0, $3, $FF, $F2
DATALH296N763C_7: dc.b $0, $3
	dc.b $6, $4, $0, $0, $0, $0, $FF, $F8
	dc.b $5, $8, $0, $2, $0, $1, $FF, $DA
	dc.b $10, $8, $0, $1, $0, $0, $FF, $E4
DATALH296N763C_8: dc.b $0, $2
	dc.b $11, $4, $0, $0, $0, $0, $FF, $ED
	dc.b $0, $6, $0, $2, $0, $1, $FF, $E7
DATALH296N763C_9: dc.b $0, $9
	dc.b $F0, $8, $0, $0, $0, $0, $0, $4
	dc.b $F1, $4, $0, $1, $0, $0, $FF, $F7
	dc.b $F5, $8, $0, $0, $0, $0, $FF, $E0
	dc.b $2, $4, $0, $1, $0, $0, $0, $3
	dc.b $FD, $8, $0, $3, $0, $1, $0, $7
	dc.b $0, $5, $0, $1, $0, $0, $FF, $EE
	dc.b $E8, $8, $0, $0, $0, $0, $FF, $EB
	dc.b $6, $5, $0, $6, $0, $3, $FF, $DB
	dc.b $F, $4, $0, $1, $0, $0, $0, $10
DATALH296N763C_A: dc.b $0, $4
	dc.b $E8, $A, $0, $0, $0, $0, $FF, $E8
	dc.b $E8, $A, $0, $9, $0, $4, $0, $0
	dc.b $0, $A, $18, $9, $18, $4, $FF, $E8
	dc.b $0, $A, $18, $0, $18, $0, $0, $0
DATALH296N763C_B: dc.b $0, $4
	dc.b $E8, $A, $0, $0, $0, $0, $FF, $E8
	dc.b $E8, $A, $8, $0, $8, $0, $0, $0
	dc.b $0, $A, $10, $0, $10, $0, $FF, $E8
	dc.b $0, $A, $18, $0, $18, $0, $0, $0
DATALH296N763C_C: dc.b $0, $1
	dc.b $FC, $0, $0, $0, $0, $0, $FF, $FC
DATALH296N763C_D: dc.b $0, $1
	dc.b $F8, $5, $0, $20, $0, $10, $FF, $F8
DATALH296N763C_E: dc.b $0, $3
	dc.b $E8, $C, $0, $0, $0, $0, $FF, $F8
	dc.b $F0, $7, $0, $4, $0, $2, $0, $8
	dc.b $10, $C, $0, $C, $0, $6, $FF, $F8
DATALH296N763C_F: dc.b $0, $2
	dc.b $E8, $A, $0, $0, $0, $0, $0, $0
	dc.b $0, $A, $0, $9, $0, $4, $0, $0
DATALH296N763C_10: dc.b $0, $3
	dc.b $E8, $8, $0, $0, $0, $0, $FF, $F8
	dc.b $F0, $B, $0, $3, $0, $1, $0, $0
	dc.b $10, $8, $0, $F, $0, $7, $FF, $F8
DATALH296N763C_11: dc.b $0, $3
	dc.b $E8, $8, $0, $0, $0, $0, $FF, $F8
	dc.b $F0, $E, $0, $3, $0, $1, $FF, $F8
	dc.b $8, $9, $0, $F, $0, $7, $FF, $F8
DATALH296N763C_12: dc.b $0, $2
	dc.b $E8, $6, $0, $0, $0, $0, $FF, $F8
	dc.b $0, $6, $0, $6, $0, $3, $FF, $F8
DATALH296N763C_13: dc.b $0, $3
	dc.b $E8, $8, $8, $0, $8, $0, $FF, $F0
	dc.b $F0, $E, $8, $3, $8, $1, $FF, $E8
	dc.b $8, $9, $8, $F, $8, $7, $FF, $F0
DATALH296N763C_14: dc.b $0, $3
	dc.b $E8, $8, $8, $0, $8, $0, $FF, $F0
	dc.b $F0, $B, $8, $3, $8, $1, $FF, $E8
	dc.b $10, $8, $8, $F, $8, $7, $FF, $F0
DATALH296N763C_15: dc.b $0, $2
	dc.b $E8, $A, $8, $0, $8, $0, $FF, $E8
	dc.b $0, $A, $8, $9, $8, $4, $FF, $E8
DATALH296N763C_16: dc.b $0, $3
	dc.b $E8, $C, $8, $0, $8, $0, $FF, $E8
	dc.b $F0, $7, $8, $4, $8, $2, $FF, $E8
	dc.b $10, $C, $8, $C, $8, $6, $FF, $E8
DATALH296N763C_17: dc.b $0, $0
	even