#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------------------
# Config — adjust these to match your repo layout/tools
# ------------------------------------------------------------------------------
OUT_DIR="data"
OUT_FILE="${OUT_DIR}/art_tile_sizes.txt"

# Kosinski (level tiles) input glob
KOS_GLOB="art/kosinski/*.bin"           # e.g. assets/tiles/EHZ.kos

# Nemesis (object art) input glob (recursive)
NEM_GLOB="art/nemesis/*.bin"      # e.g. assets/objects/monitor/powerups.nem

# Decompressor tools (CLI). Provide full paths or rely on $PATH.
KOSDEC="${KOSDEC:-tools/kosdec}"        # or: kosdec
NEMDEC="${NEMDEC:-tools/nemdec}"     # or: nemdec

TMP_DIR="$(mktemp -d -t artcalc.XXXXXX)"

cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

mkdir -p "$OUT_DIR"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
bytes_to_tiles() {
  # $1: byte_count -> prints 0xXXXX (tiles)
  local bytes="$1"
  local tiles=$(( bytes / 32 ))
  printf "0x%04X" "$tiles"
}

zone_from_path() {
  # Turn assets/tiles/EHZ.kos -> EHZ
  local p="$1"
  local f="${p##*/}"         # EHZ.kos
  echo "${f%.*}"             # EHZ
}

name_from_path() {
  # Turn assets/objects/monitor/powerups.nem -> monitor/powerups
  local p="$1"
  local f="${p%.bin}"
  echo "${f#assets/objects/}"
}

decompress_kos() {
  # these “.bin” files are already decompressed
  cp "$1" "$2"
}

decompress_nem() {
  # $1 in .nem, $2 out.raw
  "$NEMDEC" -d "$1" "$2"
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

# ------------------------------------------------------------------------------
# Write header
# ------------------------------------------------------------------------------
{
  echo "; ---------------------------------------------------------------------------"
  echo "; Generated by scripts/gen_art_sizes.sh — DO NOT COMMIT TO GAME BUILD"
  echo "; Time: $(date)"
  echo "; ---------------------------------------------------------------------------"
  echo
} > "$OUT_FILE"

# ------------------------------------------------------------------------------
# Level tiles (Kosinski)
# ------------------------------------------------------------------------------
if have_cmd "$KOSDEC"; then
  {
    echo "; Level art (Kosinski) — tile counts (tile = 32 bytes)"
    echo "; ArtTile_ArtKos_LevelArt               = \$0000  ; FG starts at tile 0"
  } >> "$OUT_FILE"

  shopt -s nullglob
  for kos in $KOS_GLOB; do
    zone="$(zone_from_path "$kos")"
    out="${TMP_DIR}/${zone}.raw"
    if decompress_kos "$kos" "$out"; then
      bytes=$(stat -c%s "$out")
      tiles_hex=$(bytes_to_tiles "$bytes")
      printf "ArtTile_ArtKos_NumTiles_%-12s = %s\n" "$zone" "$tiles_hex" >> "$OUT_FILE"
    else
      echo "; WARN: failed to decompress $kos" >> "$OUT_FILE"
    fi
  done
  echo >> "$OUT_FILE"
else
  {
    echo "; WARN: Skipping Kosinski section — missing KOSDEC ($KOSDEC)"
    echo
  } >> "$OUT_FILE"
fi

# ------------------------------------------------------------------------------
# Object art (Nemesis)
# ------------------------------------------------------------------------------
if have_cmd "$NEMDEC"; then
  {
    echo "; Object art (Nemesis) — base tiles are per PLR, counts here are useful for packing"
  } >> "$OUT_FILE"

  shopt -s globstar nullglob
  for nem in $NEM_GLOB; do
    name="$(name_from_path "$nem")"               # e.g. monitor/powerups
    sym="ArtTile_ArtNem_NumTiles_${name//\//_}"  # ArtTile_ArtNem_NumTiles_monitor_powerups
    out="${TMP_DIR}/$(basename "$nem" .bin).raw"
    if decompress_nem "$nem" "$out"; then
      bytes=$(stat -c%s "$out")
      tiles_hex=$(bytes_to_tiles "$bytes")
      printf "%-40s = %s\n" "$sym" "$tiles_hex" >> "$OUT_FILE"
    else
      echo "; WARN: failed to decompress $nem" >> "$OUT_FILE"
    fi
  done
  echo >> "$OUT_FILE"
else
  {
    echo "; WARN: Skipping Nemesis section — missing NEMDEC ($NEMDEC)"
    echo
  } >> "$OUT_FILE"
fi

# ------------------------------------------------------------------------------
# Footer + quick guidance
# ------------------------------------------------------------------------------
{
  echo "; ---------------------------------------------------------------------------"
  echo "; Notes:"
  echo "; - Foreground (level) art occupies tiles [0 .. ArtTile_ArtKos_NumTiles_<ZONE>-1]."
  echo "; - Keep always-loaded sprite art (Std2) strictly above the max of those ranges"
  echo ";   and below Rings/HUD (e.g., ArtTile_ArtNem_Ring)."
  echo "; - These values are for reference only and are NOT included in the ROM build."
  echo "; ---------------------------------------------------------------------------"
} >> "$OUT_FILE"

echo "Wrote ${OUT_FILE}"
